use bevy::prelude::*;
use iroh::EndpointId;
use shakmaty::Color;

use crate::core::states::GameState;
use crate::game::events::GameStartedEvent;
use crate::multiplayer::{network_protocol::NetworkMessage, BraidNetworkState, NetworkEvent};

/// Resource tracking P2P connection state
#[derive(Resource, Debug, Clone, Default)]
pub struct P2PConnectionState {
    /// Our local node ID
    pub local_node_id: Option<EndpointId>,
    /// The peer we are connected to or trying to connect to
    pub peer_node_id: Option<String>,
    /// Current connection status
    pub status: P2PConnectionStatus,
    /// Game ID for this session (generated by host)
    pub game_id: Option<u64>,
    /// Whether we are hosting or joining
    pub is_host: bool,
    /// Player color (White = host, Black = joiner for now)
    pub player_color: Option<Color>,
}

#[derive(Debug, Clone, Default, PartialEq)]
pub enum P2PConnectionStatus {
    #[default]
    Disconnected,
    Hosting,       // Waiting for peer to join
    Connecting,    // Sending invite to peer
    Connected,     // Peer accepted, waiting for game start
    InGame,        // Actively playing
    Error(String), // Connection error
}

/// Event to initiate a connection to a peer
#[derive(Message)]
pub struct ConnectToPeerEvent {
    pub peer_node_id: String,
}

/// Event to start hosting a game
#[derive(Message)]
pub struct HostGameEvent;

/// Event to accept an incoming invite
#[derive(Message)]
pub struct AcceptInviteEvent {
    pub game_id: u64,
}

/// Event to reject an incoming invite
#[derive(Message)]
pub struct RejectInviteEvent {
    pub game_id: u64,
}

/// Resource to persist peer node ID input across frames (for UI)
#[derive(Resource, Default)]
pub struct P2PUIState {
    pub peer_input: String,
    /// Error message to display if connection fails
    pub error_message: Option<String>,
}

impl P2PUIState {
    /// Validate the peer node ID input
    /// Returns Ok(()) if valid, Err with message if invalid
    pub fn validate_node_id(&self) -> Result<(), String> {
        let input = self.peer_input.trim();

        if input.is_empty() {
            return Err("Please enter a Node ID".to_string());
        }

        // Iroh node IDs are 32 bytes, which encode to ~44 chars in base58
        // Allow some flexibility: minimum 40 chars, maximum 60 chars
        if input.len() < 40 {
            return Err(format!(
                "Node ID too short ({} chars). Expected ~44 characters.",
                input.len()
            ));
        }

        if input.len() > 60 {
            return Err(format!(
                "Node ID too long ({} chars). Expected ~44 characters.",
                input.len()
            ));
        }

        // Check if it's valid base58
        match bs58::decode(input).into_vec() {
            Ok(decoded) => {
                if decoded.len() != 32 {
                    return Err(format!(
                        "Invalid Node ID format: decoded to {} bytes, expected 32 bytes",
                        decoded.len()
                    ));
                }
                Ok(())
            }
            Err(e) => Err(format!(
                "Invalid Node ID format: not valid base58 encoding ({:?})",
                e
            )),
        }
    }

    /// Clear the error message
    pub fn clear_error(&mut self) {
        self.error_message = None;
    }

    /// Set an error message
    pub fn set_error(&mut self, message: impl Into<String>) {
        self.error_message = Some(message.into());
    }
}

/// Plugin for P2P connection management
pub struct P2PConnectionPlugin;

impl Plugin for P2PConnectionPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<P2PConnectionState>()
            .init_resource::<P2PUIState>()
            .add_message::<ConnectToPeerEvent>()
            .add_message::<HostGameEvent>()
            .add_message::<AcceptInviteEvent>()
            .add_message::<RejectInviteEvent>()
            .add_systems(
                Update,
                (
                    handle_host_game,
                    handle_connect_to_peer,
                    handle_network_events,
                    handle_accept_invite,
                    handle_reject_invite,
                ),
            );
    }
}

/// Start hosting a game
fn handle_host_game(
    mut events: MessageReader<HostGameEvent>,
    mut connection_state: ResMut<P2PConnectionState>,
    network_state: Res<BraidNetworkState>,
) {
    for _ in events.read() {
        // Generate a random game ID
        let game_id: u64 = rand::random();

        connection_state.local_node_id = network_state.node_id.clone();
        connection_state.game_id = Some(game_id);
        connection_state.is_host = true;
        connection_state.status = P2PConnectionStatus::Hosting;
        connection_state.player_color = Some(Color::White);

        info!("Hosting game {}. Waiting for peer to connect...", game_id);
        info!("Share your Node ID: {:?}", network_state.node_id);
    }
}

/// Send game invite to peer
fn handle_connect_to_peer(
    mut events: MessageReader<ConnectToPeerEvent>,
    mut connection_state: ResMut<P2PConnectionState>,
    network_state: Res<BraidNetworkState>,
) {
    for event in events.read() {
        let game_id: u64 = rand::random();

        connection_state.local_node_id = network_state.node_id.clone();
        connection_state.peer_node_id = Some(event.peer_node_id.clone());
        connection_state.game_id = Some(game_id);
        connection_state.is_host = false;
        connection_state.status = P2PConnectionStatus::Connecting;
        connection_state.player_color = Some(Color::Black);

        // Decode peer ID from bs58
        let peer_endpoint_id = match bs58::decode(&event.peer_node_id).into_vec() {
            Ok(decoded) => {
                if decoded.len() == 32 {
                    let mut bytes = [0u8; 32];
                    bytes.copy_from_slice(&decoded);
                    match iroh::EndpointId::from_bytes(&bytes) {
                        Ok(id) => Some(id),
                        Err(e) => {
                            error!("Invalid Node ID bytes: {}", e);
                            connection_state.status =
                                P2PConnectionStatus::Error("Invalid Node ID bytes".to_string());
                            None
                        }
                    }
                } else {
                    error!("Node ID wrong length: expected 32, got {}", decoded.len());
                    connection_state.status =
                        P2PConnectionStatus::Error("Node ID wrong length".to_string());
                    None
                }
            }
            Err(e) => {
                error!("Invalid base58 Node ID: {}", e);
                connection_state.status =
                    P2PConnectionStatus::Error("Invalid base58 Node ID".to_string());
                None
            }
        };

        if let Some(endpoint_id) = peer_endpoint_id {
            if network_state.connected_peers.contains(&event.peer_node_id) {
                // Already connected, send invite immediately
                info!(
                    "Already connected to {}, sending invite directly",
                    event.peer_node_id
                );
                if let Some(tx) = &network_state.message_sender {
                    let our_node_id = network_state
                        .node_id
                        .as_ref()
                        .map(|id| bs58::encode(id.as_bytes()).into_string())
                        .unwrap_or_else(|| "unknown".to_string());

                    let invite = NetworkMessage::GameInvite {
                        game_id,
                        from_node: our_node_id,
                        from_wallet: "pvp_player".to_string(), // Simplified for PvP
                    };

                    if let Err(e) = tx.send(invite) {
                        error!("Failed to send game invite: {}", e);
                        connection_state.status =
                            P2PConnectionStatus::Error(format!("Failed to send invite: {}", e));
                    } else {
                        info!(
                            "Sent game invite {} to peer {}",
                            game_id, event.peer_node_id
                        );
                    }
                }
            } else {
                if let Some(bootstrap_tx) = &network_state.bootstrap_sender {
                    if let Err(e) = bootstrap_tx.send(endpoint_id) {
                        error!("Failed to send bootstrap peer: {}", e);
                        connection_state.status =
                            P2PConnectionStatus::Error(format!("Failed to bootstrap: {}", e));
                    } else {
                        info!(
                            "Initiated connection to peer node {}. Waiting for network...",
                            event.peer_node_id
                        );
                    }
                } else {
                    error!("Network not initialized - cannot connect to peer");
                    connection_state.status =
                        P2PConnectionStatus::Error("Network not initialized".to_string());
                }
            }
        }
    }
}

/// Handle incoming network events
fn handle_network_events(
    mut network_events: MessageReader<NetworkEvent>,
    mut connection_state: ResMut<P2PConnectionState>,
    mut network_state: ResMut<BraidNetworkState>,
    mut next_state: ResMut<NextState<GameState>>,
    mut game_started: MessageWriter<GameStartedEvent>,
) {
    for event in network_events.read() {
        match event {
            NetworkEvent::PeerConnected(peer_id) => {
                info!("PeerConnected: {}", peer_id);
                network_state.connected_peers.insert(peer_id.clone());
                // If we are connecting and this is the peer we want to connect to
                if let P2PConnectionStatus::Connecting = connection_state.status {
                    if Some(peer_id.clone()) == connection_state.peer_node_id {
                        let game_id = connection_state.game_id.unwrap_or_else(rand::random);
                        connection_state.game_id = Some(game_id);

                        if let Some(tx) = &network_state.message_sender {
                            let our_node_id = network_state
                                .node_id
                                .as_ref()
                                .map(|id| bs58::encode(id.as_bytes()).into_string())
                                .unwrap_or_else(|| "unknown".to_string());

                            let invite = NetworkMessage::GameInvite {
                                game_id,
                                from_node: our_node_id,
                                from_wallet: "pvp_player".to_string(), // Simplified for PvP
                            };

                            if let Err(e) = tx.send(invite) {
                                error!("Failed to send game invite: {}", e);
                                connection_state.status = P2PConnectionStatus::Error(format!(
                                    "Failed to send invite: {}",
                                    e
                                ));
                            } else {
                                info!(
                                    "Sent game invite {} to peer {} after network connect",
                                    game_id, peer_id
                                );
                            }
                        } else {
                            error!("Network not initialized - cannot send invite");
                            connection_state.status =
                                P2PConnectionStatus::Error("Network not initialized".to_string());
                        }
                    }
                }
            }
            NetworkEvent::MessageReceived(msg) => {
                match msg {
                    NetworkMessage::GameInvite {
                        game_id, from_node, ..
                    } => {
                        info!(
                            "Received game invite from {} for game {}",
                            from_node, game_id
                        );

                        if connection_state.is_host {
                            info!(
                                "Peer joined our hosted game! Auto-accepting invite from {}",
                                from_node
                            );
                            connection_state.peer_node_id = Some(from_node.clone());
                            connection_state.game_id = Some(*game_id);
                            connection_state.status = P2PConnectionStatus::Connected;

                            if let Some(tx) = &network_state.message_sender {
                                let response = NetworkMessage::InviteResponse {
                                    game_id: *game_id,
                                    accepted: true,
                                };
                                if let Err(e) = tx.send(response) {
                                    error!("Failed to send invite acceptance: {}", e);
                                    connection_state.status = P2PConnectionStatus::Error(format!(
                                        "Failed to accept invite: {}",
                                        e
                                    ));
                                } else {
                                    info!("Sent InviteResponse(accepted) for game {}", game_id);
                                }
                            } else {
                                error!("Network not initialized - cannot accept invite");
                                connection_state.status = P2PConnectionStatus::Error(
                                    "Network not initialized".to_string(),
                                );
                            }
                        } else {
                            connection_state.peer_node_id = Some(from_node.clone());
                            connection_state.game_id = Some(*game_id);
                            connection_state.status = P2PConnectionStatus::Connected;
                            connection_state.player_color = Some(Color::Black);
                        }
                    }

                    NetworkMessage::InviteResponse { game_id, accepted } => {
                        if connection_state.game_id == Some(*game_id) {
                            if *accepted {
                                info!("Host accepted invite for game {}", game_id);
                                connection_state.status = P2PConnectionStatus::InGame;

                                if let Some(tx) = &network_state.message_sender {
                                    let local_str = bs58::encode(
                                        connection_state.local_node_id.as_ref().unwrap().as_bytes(),
                                    )
                                    .into_string();
                                    let peer_str =
                                        connection_state.peer_node_id.clone().unwrap_or_default();

                                    // Host (peer) is White; joiner (us) is Black
                                    let white_player = peer_str.clone();
                                    let black_player = local_str.clone();

                                    let start_msg = NetworkMessage::GameStart {
                                        game_id: *game_id,
                                        white_player: white_player.clone(),
                                        black_player: black_player.clone(),
                                        initial_fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1".to_string(),
                                    };

                                    let _ = tx.send(start_msg);

                                    // Joiner won't receive its own gossip broadcast,
                                    // so transition to InGame directly here.
                                    game_started.write(GameStartedEvent {
                                        game_id: *game_id,
                                        white_player,
                                        black_player,
                                    });
                                    next_state.set(GameState::InGame);
                                }
                            } else {
                                info!("Host rejected invite for game {}", game_id);
                                connection_state.status = P2PConnectionStatus::Disconnected;
                                connection_state.game_id = None;
                            }
                        }
                    }

                    NetworkMessage::GameStart {
                        game_id,
                        white_player,
                        black_player,
                        initial_fen: _,
                    } => {
                        if connection_state.game_id == Some(*game_id) {
                            info!(
                                "Game {} started! White: {}, Black: {}",
                                game_id, white_player, black_player
                            );
                            connection_state.status = P2PConnectionStatus::InGame;

                            game_started.write(GameStartedEvent {
                                game_id: *game_id,
                                white_player: white_player.clone(),
                                black_player: black_player.clone(),
                            });

                            next_state.set(GameState::InGame);
                        }
                    }

                    _ => {}
                }
            }
            _ => {}
        }
    }
}

/// Accept an incoming game invite
fn handle_accept_invite(
    mut events: MessageReader<AcceptInviteEvent>,
    connection_state: ResMut<P2PConnectionState>,
    network_state: Res<BraidNetworkState>,
) {
    for event in events.read() {
        if connection_state.game_id == Some(event.game_id) {
            if let Some(tx) = &network_state.message_sender {
                let response = NetworkMessage::InviteResponse {
                    game_id: event.game_id,
                    accepted: true,
                };

                if let Err(e) = tx.send(response) {
                    error!("Failed to send invite acceptance: {}", e);
                } else {
                    info!("Accepted invite for game {}", event.game_id);
                }
            }
        }
    }
}

/// Reject an incoming game invite
fn handle_reject_invite(
    mut events: MessageReader<RejectInviteEvent>,
    mut connection_state: ResMut<P2PConnectionState>,
    network_state: Res<BraidNetworkState>,
) {
    for event in events.read() {
        if connection_state.game_id == Some(event.game_id) {
            if let Some(tx) = &network_state.message_sender {
                let response = NetworkMessage::InviteResponse {
                    game_id: event.game_id,
                    accepted: false,
                };

                if let Err(e) = tx.send(response) {
                    error!("Failed to send invite rejection: {}", e);
                } else {
                    info!("Rejected invite for game {}", event.game_id);
                }
            }

            // Reset connection state
            connection_state.status = P2PConnectionStatus::Disconnected;
            connection_state.game_id = None;
            connection_state.peer_node_id = None;
        }
    }
}
