[features]
seeds = true
skip-lint = false

[programs.localnet]
xfchess_game = "A5HtSnmyTPohayj9633D9queFFmL2ep6u45nv1v4Wj3W"

[programs.devnet]
xfchess_game = "A5HtSnmyTPohayj9633D9queFFmL2ep6u45nv1v4Wj3W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
