[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
xfchess_game = "JBt1hnamsAzvtggRZcom6zT5kg1eYM2R2yokqnocXUD7"

[programs.localnet]
xfchess_game = "8tevgspityTTG45KvvRtWV4GZ2kuGDBYWMXouFGquyDU"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[hooks]
