//! Search parameters tuned from Sarah chess engine (lostnthought/sarah)
//!
//! These values are copied from Sarah's SPSA-tuned defaults.
//! A future plan may implement an actual SPSA self-play tuner.

/// All configurable search parameters in one place.
#[derive(Clone, Debug)]
pub struct SearchParams {
    pub aspiration_base: i32,
    pub aspiration_mul: i32,
    pub qdelta_margin: i32,
    pub qsee_margin: i32,
    pub check_prune_margin: i32,
    pub rfp_depth: i32,
    pub rfp_base: i32,
    pub rfp_mul: i32,
    pub rfp_improving: i32,
    pub lmr_depth: i32,
    pub lmr_move_start: i32,
    pub lmr_hd: i32,
    pub lmr_quiet_mul: f64,
    pub lmr_quiet_base: f64,
    pub lmp_depth: i32,
    pub lmp_base: i32,
    pub lmp_improving: i32,
    pub lmp_depth_pow: f64,
    pub futility_depth: i32,
    pub futility_base: i32,
    pub futility_mul: i32,
    pub futility_hist_mul: i32,
    pub futility_improving: i32,
    pub razor_depth: i32,
    pub razor_base: i32,
    pub razor_mul: i32,
    pub razor_improving: i32,
    pub nmp_base: i32,
    pub nmp_mul: i32,
    pub nmp_slope: i32,
    pub probcut_depth: i32,
    pub probcut_improving: i32,
    pub probcut_base: i32,
    pub iid_depth: i32,
    pub chist_depth: i32,
    pub chist1_margin: i32,
    pub chist2_margin: i32,
    pub see_depth: i32,
    pub see_quiet_margin: i32,
    pub see_nonquiet_margin: i32,
    pub se_depth: i32,
    pub se_depth_margin: f64,
    pub qhistory_mul: i32,
    pub qhistory_base: i32,
    pub qhpen_mul: i32,
    pub qhpen_base: i32,
    pub chistory_mul: i32,
    pub chistory_base: i32,
    pub chpen_mul: i32,
    pub chpen_base: i32,
    pub beta_bonus: i32,
    pub corrhist_grain: i32,
    pub corrhist_weight: i32,
    pub corrhist_max: i32,
    pub corr_depth_base: i32,
    pub corr_ch_weight: i32,
    pub corr_np_weight: i32,
    pub corr_pawn_weight: i32,
    pub corr_kbn_weight: i32,
    pub corr_kqr_weight: i32,
    pub eval_scale: f64,
}

impl Default for SearchParams {
    fn default() -> Self {
        Self::sarah_tuned()
    }
}

impl SearchParams {
    /// Sarah's SPSA-tuned defaults (from search.c init_search_params)
    pub const fn sarah_tuned() -> Self {
        Self {
            aspiration_base: 63,
            aspiration_mul: 3,
            qdelta_margin: 287,
            qsee_margin: -67,
            check_prune_margin: 60,
            rfp_depth: 4,
            rfp_base: 4,
            rfp_mul: 37,
            rfp_improving: 70,
            lmr_depth: 3,
            lmr_move_start: 3,
            lmr_hd: 16760,
            lmr_quiet_mul: 0.613,
            lmr_quiet_base: 1.225,
            lmp_depth: 4,
            lmp_base: 8,
            lmp_improving: 1,
            lmp_depth_pow: 1.48,
            futility_depth: 2,
            futility_base: 209,
            futility_mul: 209,
            futility_hist_mul: 39,
            futility_improving: 21,
            razor_depth: 1,
            razor_base: 248,
            razor_mul: 112,
            razor_improving: 132,
            nmp_base: 11,
            nmp_mul: 626,
            nmp_slope: 320,
            probcut_depth: 7,
            probcut_improving: 73,
            probcut_base: 129,
            iid_depth: 6,
            chist_depth: 3,
            chist1_margin: -895,
            chist2_margin: -915,
            see_depth: 2,
            see_quiet_margin: -76,
            see_nonquiet_margin: -105,
            se_depth: 7,
            se_depth_margin: 1.26,
            qhistory_mul: 236,
            qhistory_base: 155,
            qhpen_mul: 164,
            qhpen_base: 85,
            chistory_mul: 136,
            chistory_base: 223,
            chpen_mul: 165,
            chpen_base: 92,
            beta_bonus: 50,
            corrhist_grain: 135,
            corrhist_weight: 260,
            corrhist_max: 8218,
            corr_depth_base: 1,
            corr_ch_weight: 284,
            corr_np_weight: 103,
            corr_pawn_weight: 121,
            corr_kbn_weight: 6,
            corr_kqr_weight: 269,
            eval_scale: 1.019,
        }
    }
}
